## -- Part 1 -- PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Tensors
## Creating Tensors

In [ ]:
# Scalar (a single number)
# Naming convention -> Lowercase (a)
# Tensors are created using 'torch.tensor()'
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor dimensions
# ndim = Number of dimensions
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector (one dimensional tensor)
# Naming convention -> Lowercase (y)
# Vector is defined by magnitude and direction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Get tensor dimensions
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX (two dimensional tensor)
# Naming convention -> Uppercase (Q)
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Number of MATRIX dimensions
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR (any dimension tensor)
# Naming convention -> Uppercase (X)
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# TENSOR ndim
TENSOR.ndim

3

In [ ]:
# TENSOR shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# Exercice : My Tensor

vTensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                        [[3, 2, 1],
                         [9, 8, 7],
                         [6, 5, 4]]])
vTensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 2, 1],
         [9, 8, 7],
         [6, 5, 4]]])

In [ ]:
# Dimensions
vTensor.ndim

3

In [ ]:
# Shape
vTensor.shape
# torch.Size([2, 3, 3])
# Trad : 2 entrées de 3x3

torch.Size([2, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many neural networks learn is that theu start with tensors fill of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
# See doc -> torch.rand
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2189, 0.2482, 0.6883, 0.5939],
        [0.7001, 0.1893, 0.6139, 0.8200],
        [0.8718, 0.8614, 0.3752, 0.8084]])

In [ ]:
# Number of random tensor dimensions
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all one
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# dtype -> Default data type
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range
#deprecated_one_to_ten = torch.range(1, 10)
#deprecated_one_to_ten

# Deprecated use torch.arange
one_to_ten = torch.arange(1, 11)
one_to_ten


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# With parameters
torch.arange(start=1, end=11, step=2)

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like
# -> Creates a tensor with the same shape as an other, but filled with zeros
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Exercice

In [ ]:
# Create a random 3,3 tensor
my_test_tensor = torch.rand(2, 3, 3)
my_test_tensor

tensor([[[0.9729, 0.1406, 0.3052],
         [0.8643, 0.2209, 0.7587],
         [0.3212, 0.3089, 0.6618]],

        [[0.7750, 0.8081, 0.8560],
         [0.8974, 0.8651, 0.8147],
         [0.0615, 0.1978, 0.5172]]])

In [ ]:
# Create a tensor like with the shape of my_test_tensor
# Filled with ones
my_test_tensor_like = torch.ones_like(my_test_tensor)
my_test_tensor_like

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
# Create a tensor like with the shape of my_test_tensor
# Filled with random values
my_test_random_tensor_like = torch.rand_like(my_test_tensor)
my_test_random_tensor_like

tensor([[[0.6053, 0.9108, 0.7718],
         [0.0899, 0.2035, 0.4340],
         [0.2085, 0.2601, 0.3945]],

        [[0.2081, 0.1082, 0.1405],
         [0.0710, 0.4858, 0.0247],
         [0.6744, 0.9978, 0.1954]]])

___________________________________________

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning
1. Tensores not right data type
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What data type is the tensor (e.G. float16, float32, float64 ... AKA precision level)
                               device= None, # What device is your tensor on (Default "cpu")
                               requires_grad=False) # If you want PyToch to track the gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Result is float 32 even though we set None
# Because Float 32 is the default type
float_32_tensor.dtype

torch.float32

In [ ]:
# Converting a 32bits into a 16bits tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Multiply float 16 by float 32 tensor (just to try)
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Create an int 32bits tensor
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
# Multiply float 32bit by int 32 bits tensors
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor

1. Tensores not right data type - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7512, 0.8749, 0.0064, 0.7086],
        [0.8286, 0.6417, 0.2680, 0.0808],
        [0.8134, 0.4082, 0.5980, 0.8452]])

In [ ]:
# Find out details about some_tensor
print("## Some tensor ##")
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

## Some tensor ##
tensor([[0.7512, 0.8749, 0.0064, 0.7086],
        [0.8286, 0.6417, 0.2680, 0.0808],
        [0.8134, 0.4082, 0.5980, 0.8452]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [ ]:
# multiply it by 10
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
# substract 100
tensor = torch.tensor([1, 2, 3])
tensor - 100

tensor([-99, -98, -97])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # Multiply `tensor`by `10`

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10) # addition
torch.div(tensor, 10) # division

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplications
(see math is fun : matrix multiplication)

Two main ways of performing multiplication in NN and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules that performing matrix multiplications need to satisfy:
1. The **inner dimensions** must match:
* (3, **2**) @ (**3**, 2) won't work
* (2, **3**) @ (**3**, 2) will work
* (3, **2**) @ (**2**, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:
* (**2**, 3) @ (3, **2**) -> (**2, 2**)
* (**3**, 2) @ (2, **3**) -> (**3, 3**)

In [ ]:
# Element with multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor) # Matrix multiplication function of torch

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# Manual calculation time
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.12 ms, sys: 0 ns, total: 3.12 ms
Wall time: 3.34 ms


In [ ]:
# Calculation time with matmul()
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.29 ms, sys: 14 µs, total: 1.31 ms
Wall time: 1.26 ms


tensor(14)

### One of the most common errors : Shape Error

In [ ]:
# Shapes for matrix multiplications
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_a, tensor_b) # torch.mm() is an alias for torch.matmul()
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our sensor shape issies, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_b, tensor_b.shape # Original

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b.T, tensor_b.T.shape # T stands for transpose

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication works when tensor_b is transposed
print(f"Original shapes: tensor_a = {tensor_a.shape}, tensor_B = {tensor_b.shape}")
print(f"New shapes: tensor_a = {tensor_a.shape}, tensor_B = {tensor_b.T.shape}")
print(f"Multiplying: {tensor_a.shape} @ {tensor_b.T.shape} -> Inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output)
print(f"\nOutput shapes: {output.shape}")

Original shapes: tensor_a = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_a = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) -> Inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shapes: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32
# datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
# Find the min, max position in tensor
(torch.argmin(x), x.argmin(), torch.argmax(x), x.argmax())

(tensor(0), tensor(0), tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each others (**vstack**) or side-by-side (**hstack**)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - adds a `1`dimension to a target sensor
* **Permute** - returns a view of the input wisth dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch

x = torch.arange(1., 10.)
x_reshaped = x.reshape(1,9)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
y = torch.arange(1., 11.)
# Add an extra dimension
y_reshaped = y.reshape(1, 10) # Must match the number of elements of given tensor (here 1*10=10)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
y_reshaped2 = y.reshape(2, 5) # Must match the number of elements of given tensor (here 2*5=10)
y_reshaped2, y_reshaped2.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because the view of a tensor shares the same memory address as the original)
z[:, 0] = 5 # changes the first entry of z to "5"
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # Play around with dim= to get different shapes
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
# Squeze
# torch.squeeze() - Removes all single dimensions from a target sensor

print(f"Previous sensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew sensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous sensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New sensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# ermute the original tensor to rearrange the axis (or dim order)
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3) # Create a (1, 9) then shapes it in (1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our nexw tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
 # You can also use ":" to select "all" of a target dimension
 x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this PyTorch has fonctionallity to interract with it.

* Data in NumPy, want in PyTouch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning : datatype may change (see bellow)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # Default NumPy datatype is float64

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype # Default PyTorch datatype is float32

torch.float32

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor # Only the array has changed

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype # This time it's float32

dtype('float32')

## Reproduciblity (trying to take random out of random)

In short how a neural network learns:

`start with random numbers-> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially waht the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.0496, 0.9941, 0.7202, 0.7492],
        [0.1726, 0.6793, 0.7602, 0.6025],
        [0.4356, 0.4574, 0.1377, 0.7056]])
tensor([[0.5998, 0.7447, 0.1693, 0.8524],
        [0.9557, 0.3023, 0.6832, 0.8519],
        [0.6331, 0.2021, 0.5371, 0.9070]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


tensor([[0.1053, 0.2695, 0.3588,  ..., 0.3139, 0.4654, 0.1612],
        [0.1568, 0.2083, 0.3289,  ..., 0.8649, 0.2726, 0.3998],
        [0.0026, 0.8346, 0.8788,  ..., 0.3970, 0.8703, 0.7563],
        ...,
        [0.6735, 0.0030, 0.7060,  ..., 0.2862, 0.8223, 0.7242],
        [0.8472, 0.4131, 0.0372,  ..., 0.8879, 0.2405, 0.6871],
        [0.7293, 0.0805, 0.6438,  ..., 0.4062, 0.8907, 0.9898]])

## Rinning tensors and PuTorch objects on GPUs a(and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA

### 1. Getting a GPU

* **Easiest** - Google collab for free GPU (+ upgrade options)
* **Use your own GPU** - Takes a little setup and investments
* **Use cloud computig** - AWS? GCP, Azure...


In [ ]:
# GPU info
!nvidia-smi

Mon Feb  3 16:29:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

see(https://www.learnpytorch.io/pytorch_cheatsheet/)

In [ ]:
# Check for the GPU access with PyTorch
import torch

torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code (access GPU only if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of GPUs / devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computation

In [ ]:
# Create a tensor (default is on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# <ipython-input-9-b7da913938a5> in <cell line: 0>()
#       1 # If tensor is on GPU, can't transform it to NumPy
# ----> 2 tensor_on_gpu.numpy()

# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [ ]:
# To fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu # remains unchanged

tensor([1, 2, 3], device='cuda:0')

## Exercices

In [ ]:
# 2. Create a random tensor with shape (7, 7).
import torch

tensor = torch.rand(7, 7)

tensor5 = torch.matmul(tensor3, tensor4.T)
tensor5, tensor5.shape

(tensor([[2.0572],
         [1.5321],
         [2.0941],
         [1.4171],
         [1.7642],
         [1.3841],
         [1.0553]]),
 torch.Size([7, 1]))

In [ ]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor2 = torch.rand(1, 7)
torch.matmul(tensor, tensor2.T)

In [ ]:
# 4. Set the random seed to 0 and do 2 & 3 over again.
RANDOM_SEED = 27
torch.manual_seed(RANDOM_SEED)
tensor3 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensor4 = torch.rand(1, 7)

In [ ]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
torch.cuda.manual_seed(1234)

In [ ]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

torch.manual_seed(1234)
tensor1 = torch.rand(2, 3)
torch.manual_seed(1234)
tensor2 = torch.rand(2, 3)

cudaTensor1 = tensor1.to("cuda")
cudaTensor2 = tensor2.to("cuda")
cudaTensor1, cudaTensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [ ]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

output = torch.matmul(cudaTensor1, cudaTensor2.T)
output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
# 8. Find the maximum and minimum values of the output of 7.
# 9. Find the maximum and minimum index values of the output of 7.


valMin = torch.min(output)
valMax = torch.max(output)
indexMin = torch.argmin(output)
indexMax = torch.argmax(output)

valMin, valMax,indexMin, indexMax


(tensor(0.2161, device='cuda:0'),
 tensor(0.6287, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'))

In [ ]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

tensor = torch.rand(1, 1, 1, 10)
tensor2 = tensor.squeeze()
tensor, tensor.shape, tensor2, tensor2.shape

(tensor([[[[0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216,
            0.5247, 0.6688]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247,
         0.6688]),
 torch.Size([10]))